// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzvycV45jiYxlC4bEkS-Ob8C-JxjBcgB8',
    appId: '1:995591283521:web:39e97ebae1f9817c9837c0',
    messagingSenderId: '995591283521',
    projectId: 'desafio-flutter-cab0d',
    authDomain: 'desafio-flutter-cab0d.firebaseapp.com',
    storageBucket: 'desafio-flutter-cab0d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEZ6uNbw--ZiFWLyWKm6qha_I_M72Jj3o',
    appId: '1:995591283521:android:e57b26f254f75f519837c0',
    messagingSenderId: '995591283521',
    projectId: 'desafio-flutter-cab0d',
    storageBucket: 'desafio-flutter-cab0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCGixfOovGRo96CePIWWEIyw9U4Povn4c',
    appId: '1:995591283521:ios:d05146b746fc3dfd9837c0',
    messagingSenderId: '995591283521',
    projectId: 'desafio-flutter-cab0d',
    storageBucket: 'desafio-flutter-cab0d.firebasestorage.app',
    iosBundleId: 'com.example.desafioFlutter',
  );
}
